server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location /users {
        proxy_pass http://user:9001;
    }

    location /products {
        proxy_pass http://product:9003;
    }

    location /filter {
        proxy_pass http://product:9003;
    }

    location /cart {
        proxy_pass http://cart:9002;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
