name: lrn-k86


services:
  db:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo-data:/data/db



  user:
    build: ./User
    image: user
    ports:
      - "9001:3001"
    command: node server.js
    depends_on:
    - db

  cart:
    build: ./Cart
    image: cart
    ports:
      - "9002:3003"
    command: node server.js 
    depends_on:
    - db 

  product:
    build: ./Product
    image: product
    ports:
      - "9003:3002"
    command: node server.js
    depends_on: 
    - db
  
  frontend:
    build: ./frontend
    image: frontend
    ports:
      - "9000:80"
    depends_on:
      - user
      - cart
      - product
    labels:
      kompose.service.type: nodeport
    
volumes:
  mongo-data: